language: node_js
node_js:
  - "10.15.3"
dist: trusty
sudo: required

before_script:
  - npm install

script:
  - npm run build
  - bin/fmpp

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master

notifications:
  on_success: false
  on_failure: change
